---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-appmatt1-repo
  namespace: demo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ocp-rhdh-poc/my-quarkus-appmatt1-gitops.git
